coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header, diff, flags"
  require_base: false
